language: php
sudo: required
dist: trusty

php:
  - 7.2

addons:
  chrome: stable

install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - mysql --host=localhost --user=root --password=
  - CREATE SCHEMA `grupo_acm`;
  - exit

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk