sudo: required
language: php
dist: trusty

php:
  - 7.1.3

install:
- travis_retry composer install --no-interaction

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - php artisan key:generate
  - php artisan migrate --step
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve > /dev/null 2>&1 &


script:
  - vendor/bin/phpunit
  - php artisan dusk --env=testing