language: php
sudo: required
dist: trusty

php:
  - 7.2

addons:
  chrome: stable
  
before_install:
  - mysql -e 'CREATE DATABASE grupo_acm CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk