sudo: required
language: php
dist: trusty

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --step
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &


script:
  - vendor/bin/phpunit
  - php artisan duke